# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAdTargetingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(db_index=True, max_length=128)),
                ('platform_id', models.CharField(max_length=128)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.CharField(max_length=256, null=True)),
                ('path', models.CharField(max_length=256, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('audience_reach', models.IntegerField()),
                ('base_audience_reach', models.IntegerField()),
                ('bias_normalizer', models.BooleanField(default=False, help_text='Use this record to normalize interest biases')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biased_index', models.FloatField(db_index=True)),
                ('unbiased_index', models.FloatField(db_index=True, null=True)),
                ('opportunity_score', models.FloatField(db_index=True)),
                ('reach_audience', models.IntegerField()),
                ('reach_base', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.FacebookAdTargetingCategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_id', models.IntegerField(help_text='The ID of the audience we are profiling')),
                ('base_audience_id', models.IntegerField(help_text='The ID of the base audience for the profile')),
                ('brand_id', models.IntegerField(db_index=True, help_text='brand ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creator', models.IntegerField(help_text='bouncer user ID', null=True)),
                ('name', models.CharField(db_index=True, max_length=191, null=True)),
                ('instagram_placement', models.BooleanField(db_index=True, default=False)),
                ('latest_profile', models.ForeignKey(help_text='The most recently created related Profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='example.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Target'),
        ),
    ]
