# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20161011_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledatum',
            name='profile',
        ),
    ]
